### ISSUE TITLE
Correlation between NimBLE and ESP-IDF

### ISSUE THREAD

**Issue by aallard** [h2zero/esp-nimble-component#5]
I'm trying to create a specific BLE advertisement that is 16 bit.  In the ESP-IDF way, I would set some advertisement parameters about the GAP Ad type such as:  advParams.adv_type  = ADV_TYPE_IND, which in their API is defined as "Service Data - 16-bit UUID" and defined as 0x16.

Also, I usually write the Ad data raw to the device using their API call like this:  esp_ble_gap_config_adv_data_raw(msg, length)

Is there an equivalent way to handle these in Nimble?  Thank you.

**Comment by h2zero** [comment]
Hello, yes you can do this. You would want to create an instance of `NimBLEAdvertisementData` and pass that to the advertising.
```
NimBLEAdvertisementData advData;
advData.addData(&data, datalen);
pAdv= NimBLEDevice::getAdvertising();
pAdv->setAdvertisementData(advData);
pAdv->start();
```
Please see the other options available [here](https://github.com/h2zero/NimBLE-Arduino/blob/e46123a084e0aa336e4cbdd52bf001dac71e5afb/src/NimBLEAdvertising.h)

**Comment by aallard** [comment]
Thank you very much!  I appreciate it.
